### ISSUE TITLE
Add history states support

### ISSUE THREAD

**Issue by nsk90** [nsk90/kstatemachine#14]
planning to add shallow history state and deep history state

**Comment by mashtonian** [comment]
Hi,

I'm interested in this as I am trying to implement an "Undo" function that allows the machine to go "backwards" through previous states.

As I exit each state, I store it in an undoList, then when processing the Undo event, I pass that state as an argument and attempt to set `targetState` to it, in the `onTriggered` listener of the Undo event:

```

when (shot) {
            is UNDO -> {
                val undoState: State? = undoList.removeLastOrNull()
                if (undoState != null) {
                    stateMachine.processEvent(shot, argument = undoState)
                }
            }

            else -> stateMachine.processEvent(shot)
        }

...

private val stateMachine = createStateMachine {
        onTransition {
            if (it.transition.sourceState.name != null) {
                println("Exiting state ${it.transition.sourceState.name}")
                println("Entering state ${it.direction.targetState?.name}")
                if (it.event !is UNDO)
                    undoList.add(it.transition.sourceState as State)
            }
        }

        transition<UNDO> {
            onTriggered {
                targetState = it.argument as State
                removeLastShot()
            }
        }

...

```

Unfortunately this doesn't work.

I also can't set the targetState in `it.direction`, as that is immutable.

Can you advise if this is possible?

**Comment by nsk90** [comment]
Try using conditional transition which allows to calculate target state in "runtime".
https://github.com/nsk90/kstatemachine/wiki#conditional-transitions

I am planning to implement this possibility, but it is not finished yet, and there is still a lot of work to do until complete.

**Comment by mashtonian** [comment]
Perfect, I got it working nicely.

I'll look out for a future release with it built in!

Thanks (again) for your help.

**Comment by nsk90** [comment]
History state added in https://github.com/nsk90/kstatemachine/releases/tag/v0.14.0

**Comment by nsk90** [comment]
issue for undo() functionality #44

**Comment by nsk90** [comment]
@mashtonian you can try undo functionality in https://github.com/nsk90/kstatemachine/releases/tag/v0.15.0 =)

**Comment by mashtonian** [comment]
Oooh, nice.

I'll have a go later this week.

Thanks!
