### ISSUE TITLE
Latest version 0.9.1 - Build failed

### ISSUE THREAD

**Issue by maros136** [nsk90/kstatemachine#26]
https://jitpack.io/com/github/nsk90/kstatemachine/kstatemachine/0.9.1/kstatemachine-0.9.1.pom

Build failed. See the log at jitpack.io

https://jitpack.io/com/github/nsk90/kstatemachine/v0.9.1/build.log

**Comment by asad-awadia** [comment]
can we get this on maven?

**Comment by nsk90** [comment]
Fixed Jitpack publishing in 0.9.2. Looks like there were some changes and now it requires maven-publish gradle plugin to be applied.

@asad-awadia I think it's not a problem, but what is the reason for that?
