### ISSUE TITLE
[CRITICAL] onFinished is notified BEFORE final onStateChange

### ISSUE THREAD

**Issue by kwasny2** [nsk90/kstatemachine#31]
fun StateMachine.stateFlow() = callbackFlow {
            val stateListener = object : StateMachine.Listener {
                override fun onStateChanged(newState: IState) {
                    trySendBlocking(newState)
                }
            }
            addListener(stateListener)
            val finishListener = object : IState.Listener {
                override fun onFinished(transitionParams: TransitionParams<*>) {
                    channel.close()
                }
            }
            addListener(finishListener)
            awaitClose {
                removeListener(stateListener)
                removeListener(finishListener)
            }
        }

Following code does not pass finalState notification. 
It is critcal bug, because it is not possible to create any reliable flow of states, rxjava observable, etc..

**Comment by nsk90** [comment]
Hi, could you post your state machine structure for testing?

**Comment by nsk90** [comment]
fixed in v0.9.5 d4184ec8

**Comment by kwasny2** [comment]
Thank you for quick action!
