### ISSUE TITLE
Initial argument for start

### ISSUE THREAD

**Issue by kwasny2** [nsk90/kstatemachine#40]
Could you provide an optional argument for start method in StateMachine interface (in the similar way as it in processEvent method)? Optional argument should be passed to initialState in state machine.

    fun start(argument: Any? = null)

I can live without it, but it will would be nice to have such parameter to avoid workaround.

**Comment by nsk90** [comment]
Done in [v0.11.0](https://github.com/nsk90/kstatemachine/releases/tag/v0.11.0)
