### ISSUE TITLE
Question: How should download progress be handled?

### ISSUE THREAD

**Issue by dave08** [nsk90/kstatemachine#46]
If I have a state data class called `data class Downloading(val progress: Int) : DefaultState()` how can I update the progress so that when I listen to state changes in the the view, I can update it accordingly?

**Comment by nsk90** [comment]
Hi, seems that your question is not related to state machine it self, so do it the same way like `Downloading` is a simple data class not related with a state.
Looks that `progress` field should be `var`? Add some notification about changes of its value (observer pattern) and listen to it in view layer.

You can look at this sample https://github.com/nsk90/android-kstatemachine-sample/blob/main/app/src/main/java/ru/nsk/kstatemachinesample/ui/main/MainViewModel.kt
See how `ammoLeft` field is updated. Just imagine that it is a progress)
The only difference that in this sample this field is stored in another class, but it does not matter, you can store it in your `Downloading` state.

**Comment by dave08** [comment]
The thing is that if I addState this Downloading class with one value and it gets copied with a different one, then it's not the same instance registered with all it's transactions... And I get new state with processEvent... So where could I put the changing state, in an onTransition block?

You're suggesting the progress itself shouldn't be a transition in the state machine at all? Then if I'm not yet at 100 when i get another (invalid) transition what would happen?

**Comment by dave08** [comment]
Say I have:

```
// Coming from another service doing this
sealed class DownloadState : Event {
   object WaitingForDownload : DownloadState()
   data class Downloading(val progress: Int) : DownloadState()
   data class MoveTo(val location: Path) : DownloadState()
}

// The state machine needs to listen to these events and transform them to states for the compose UI
val stateFlow = MutableStateFlow<DownloadState>(...)

// Just manage transitions from state to state according to events recieved from other service
val sm = createStateMachine {
...
}

// In the viewModel -- deliver state changes to the UI from the state machine
sm.onStateChanged {
// ... update UI according to state --- but progress isn't a state...?
}

```

I'd like to separate the concern of updating the UI from managing the transitions, whereas in your code in the sample -- the UI should be updated directly in the state machine, or a new abstraction layer needs to be created just to provide updates to a separate flow for progress.... I was wondering if I could use the state machine to update the progress somewhere, and provide that to update the UI --- but only when in the downloading state.

**Comment by nsk90** [comment]
```
sealed class DownloadState : Event {
   object WaitingForDownload : DownloadState()
   data class Downloading(val progress: Int) : DownloadState()
   data class MoveTo(val location: Path) : DownloadState()
}
``` 
I dont understand this construction, this is mistape or you want States to be Events at the same time?

**Comment by nsk90** [comment]
I recommend to combine notifications from state machine and from progress value updates in ViewModel into a single flow.

**Comment by dave08** [comment]
> ```
> sealed class DownloadState : Event {
>    object WaitingForDownload : DownloadState()
>    data class Downloading(val progress: Int) : DownloadState()
>    data class MoveTo(val location: Path) : DownloadState()
> }
> ```
> 
> I dont understand this construction, this is mistape or you want States to be Events at the same time?
> 
> usually there are two separate sealed classes for Events and States.

Those are really events... Coming from an older system, i'm refactoring old code. I do have a separate sealed class for states

**Comment by dave08** [comment]
> It is not possible, additional abstraction layer is really necessary. Or you have to provide 100 states with values from 0 to 100, and switching between them. State machine itself notifies only about state changes and transitions, it does not know about states properties changes.

I realized that, I guess what I really wanted was a better way to listen to those transitions from state A back to state A outside the state machine, without having to do too muchtype checking and type casting... 


> As I see slack is not working in Russia any more.
