### ISSUE TITLE
Using gradle to generate the plantUml graph

### ISSUE THREAD

**Issue by dave08** [nsk90/kstatemachine#47]
It would be nice to have a way to generate the graph from gradle w/o putting it in the app's code -- for example on Android to be able to retrieve a graph, I'd have to export it on the device, and then actually pull it from there. Whereas with gradle it could be be a git hook to generate the graph before each commit to a master branch -- or part of a CI pipeline with one of the result artifacts being such graphs.

**Comment by nsk90** [comment]
I am not sure that using gradle for this feature is really easy and convenient.

* Maybe you could wrap creating of your state machine into a `function()` and write unit test running on host OS that calls `function()` and exports machine structure to plant uml.
* Or print exportToPlantUml() output to logcat and copy/paste it on host OS, or you can have a tiny script that filters expected lines from logcat output into a file.

**Comment by dave08** [comment]
Ok, I thought of those ideas, but I just thought that it might be much more practical as a gradle task... well thanks anyways for the great library!

**Comment by nsk90** [comment]
do you have experience in parsing source code? as I see you are suggesting to make gradle task that looks through the sources and makes uml output from them, without running it. right?
