### ISSUE TITLE
Cound I apply an transition  for all states at the same time ?

### ISSUE THREAD

**Issue by xufeifeiWHU** [nsk90/kstatemachine#60]
Hi , sir 
    it is a great job ,
    when I try to apply it into project ,  I need to add a transition for all states , whatever the src state , I have tried several times ,but still could not add such transition . 

    for example :
    A -> C -> D -> E -> F
    and when a special event received, all the state need to jump to G 

    I have  read the code in test case , but no inspiration on this point yet
    Is there such a way that could add such transition now ?

thanls for your

**Comment by nsk90** [comment]
Please read "Nested states" section in docs
https://nsk90.github.io/kstatemachine/

**Comment by xufeifeiWHU** [comment]
it really works thanks
