### ISSUE TITLE
artifact in maven central has wrong content

### ISSUE THREAD

**Issue by kgignatyev** [nsk90/kstatemachine#62]
Hi, I like your library, but there is a problem, artifact in maven central has no classes only this, please fix it
![image](https://user-images.githubusercontent.com/868783/229167295-b2ca4b97-cfc9-4209-8131-07214aa589d6.png)

**Comment by kgignatyev** [comment]
hold on, looks like our cache has the content

**Comment by kgignatyev** [comment]
nope, disabled cache, loaded directly, same, no classes in jar
jar -tf ~/.m2/repository/io/github/nsk90/kstatemachine/0.22.0/kstatemachine-0.22.0.jar
META-INF/
META-INF/MANIFEST.MF
META-INF/kotlin-project-structure-metadata.json

**Comment by kgignatyev** [comment]
I need jvm one, ahh-yes could not find kstatemachine-jvm there initially, with new name it is working fine. But still there is that kstatemachine-0.22.0.jar with strange content.

**Comment by nsk90** [comment]
kstatemachine-0.22.0.jar should be fine for kotlin multiplatform projects, it has synthetic contents, but as I understand it should just reference platform specific artifacts. Actually I have not checked this on samples yet.

**Comment by kgignatyev** [comment]
that I would expect, but it does not have that

Konstantin Ignatyev
