### ISSUE TITLE
Outdated error message

### ISSUE THREAD

**Issue by lynnkale** [nsk90/kstatemachine#68]
I tried to create a state machine without enabling undo, and then attempted to undo. I got the following (very helpful!) error message:
"... createStateMachine(isUndoEnabled = true) argument to enable it ..."

However the actual parameter is `enableUndo` not `isUndoEnabled`. This message should be updated to reflect the variable name.

**Comment by nsk90** [comment]
done b9c09c9e9b82015199b740680562dd79e612f745
