### ISSUE TITLE
Add the ability to receive current state

### ISSUE THREAD

**Issue by nsk90** [nsk90/kstatemachine#8]
For example if UI attaches to statemachine that is already running. UI should know its current state, to be able to draw it.

**Comment by nsk90** [comment]
297a7c5b8fea4feb4311b323f94cab5f833e682f
Adds findState() function to enable search by name (this is not safe way)

Another option for a user is to hold a reference to a state somewhere (this is very explicit).

Question how to find states without a name is still open.

**Comment by nsk90** [comment]
done https://github.com/nsk90/kstatemachine/commit/fec47507bcd6550461ee35023962992f96c0c1fc

**Comment by asad-awadia** [comment]
How do i get the current state from a machine object?

**Comment by nsk90** [comment]
1) you can listen to per-state notifications
https://github.com/nsk90/kstatemachine/blob/master/kstatemachine/src/main/kotlin/ru/nsk/kstatemachine/IState.kt#L38

2) you can listen to machine notification about all state changes
https://github.com/nsk90/kstatemachine/blob/master/kstatemachine/src/main/kotlin/ru/nsk/kstatemachine/StateMachine.kt#L54

3) you can get current active states with activeStates() function. For machines with flat structure it will return single element list, for hierarchical machines there might be many active states at a same time.
https://github.com/nsk90/kstatemachine/blob/master/kstatemachine/src/main/kotlin/ru/nsk/kstatemachine/IState.kt#L33

**Comment by asad-awadia** [comment]
thank you
