### ISSUE TITLE
Export to PlantUml: GuardedTransitionOnBuilder are not drawn in diagram

### ISSUE THREAD

**Issue by oyanyev** [nsk90/kstatemachine#82]
When state transition is configured using GuardedTransitionOnBuilder, such a transition between states is not drawn in diagram

**Comment by oyanyev** [comment]
Sad, but true

**Comment by nsk90** [comment]
This is partly solved in https://github.com/nsk90/kstatemachine/releases/tag/v0.26.0 by unsafeCallConditionalLambdas flag
