### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by oyanyev** [nsk90/kstatemachine#88]
Hi!

I am wondering if all artifacts should have same version?
Because now it is not like this:
```
    io.github.nsk90:kstatemachine-jvm:0.25.0
    io.github.nsk90:kstatemachine-coroutines-jvm:0.24.1
```

**Comment by nsk90** [comment]
Hi, you are right, looks I forgot to publish second artifact. I will check this.

**Comment by oyanyev** [comment]
:white_check_mark: Can use 0.25.1 for both
