### ISSUE TITLE
Clarification of concurrency

### ISSUE THREAD

**Issue by asomov** [nsk90/kstatemachine#95]
The documentation clearly [states](https://nsk90.github.io/kstatemachine/#multithreading-and-concurrency):
_KStateMachine is designed to work in single thread. Concurrent modification of library classes will lead to race conditions._

Does is also mean that the calls to `processEvent() ` must be done from the same thread ?
I understand that creating the state machine with its states, listeners and transitions is single-threaded. But may be  `processEvent() ` can be called from different threads ?

**Comment by nsk90** [comment]
Hi, the short answer - yes.

Details: 
If you are using StateMachine  instance created by  createStateMachine/createStateMachineBlocking functions (with CoroutineScope specified), then it is safe to call any suspendable library methods (including processEvent()) on such instance, from any CoroutineContext (driven by any thread), as all those methods switch the CoroutineContext internally to machines one.

But if you create StateMachine instance without coroutines support (by createStdLibStateMachine) then the answer is no, as internal context switching cannot be performed in such case.

See Coroutines section in docs, there was some explanation regarding this behaviour.

**Comment by asomov** [comment]
Thank you the the quick and descriptive answer !
I think it deserves to be in the docs instead of a very short and confusing statement.

**Comment by nsk90** [comment]
I have updated the docs, and linked related sections.

**Comment by asomov** [comment]
@nsk90 may I ask you to add yet another sample to the ones provided inside the project with the way to properly create the Scope ?
_**Please don't forget that the CoroutineScope that you specify when creating a StateMachine instance sould be driven by single thread.**_
